### ISSUE TITLE
federation-subscription-tools/example/gateway-server/.env: no such file or directory

### ISSUE THREAD

**Issue by sgentile** [apollosolutions/federation-subscription-tools#11]
I pulled the project, I ran npm install, then I ran docker-compose build  - I get this error:

federation-subscription-tools/example/gateway-server/.env: no such file or directory

There aren't any clear instruction on how to run this .

**Comment by sgentile** [comment]
So I did read the instructions.   This project requires me to have an Apollo key ?   so it's not a stand alone solution ?

**Comment by sgentile** [comment]
So why doesn't Apollo provide the federation subscription tools in a npm package   - sorting through an example like this is really a bad experience for what is (should be) a very common use case.

**Comment by flyboarder** [comment]
This package has been updated with better readme instructions, apollo server 3 and typescript.
