### ISSUE TITLE
react-app Unhandled Rejection (SyntaxError): Failed to construct 'WebSocket': The URL 'undefined' is invalid.

### ISSUE THREAD

**Issue by sgentile** [apollosolutions/federation-subscription-tools#14]
Unhandled Rejection (SyntaxError): Failed to construct 'WebSocket': The URL 'undefined' is invalid.

I have this defined:

REACT_APP_GRAPHQL_URL=http://localhost:4002/graphql
REACT_APP_SOCKETIO_URL=ws://localhost:5000

but the example (and I tried this first) : REACT_APP_SOCKETIO_URL=http://localhost:5000

I still get the above error ?

**Comment by sgentile** [comment]
looks like the example had the wrong sample.envs defined

Also getting cors errors

**Comment by flyboarder** [comment]
This issue should now be resolved with the latest version.
