### ISSUE TITLE
404 error when installing the types `@types/federation-subscription-tools`

### ISSUE THREAD

**Issue by hazemalabiad** [apollosolutions/federation-subscription-tools#18]
When I tried to install the types for this package using this command `ya -D @types/federation-subscription-tools`

I got this error `error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2ffederation-subscription-tools: Not found".`
A

Any suggestions?

**Comment by flyboarder** [comment]
TypeScript has been added with the latest Apollo Server 3 update.

You do not need to install any additional packages to use typescript.
