### ISSUE TITLE
"Expected undefined to be a GraphQL schema"

### ISSUE THREAD

**Issue by tot-ra** [apollosolutions/federation-subscription-tools#8]
I've encountered this problem in react-app + subscriptions-service running in unmanaged mode 
When it tries to establish ws connection, it seems to fail with 1011 error code from graphql-ws, 
"Expected undefined to be a GraphQL schema.".. Apparently subscriptions-service doesn't have valid schema

Looks like on backend, inside `onSubscribe`, `schema` is undefined

<img width="974" alt="Screenshot 2021-07-19 at 21 53 03" src="https://user-images.githubusercontent.com/445122/126224722-cb23318e-f022-468a-848a-e8a018baa462.png">
<img width="1407" alt="Screenshot 2021-07-19 at 23 46 15" src="https://user-images.githubusercontent.com/445122/126225277-d725618a-cafb-475d-b0ab-3f3e6bd614a2.png">

After some debugging on backend I got to this error
`
An error was thrown from an 'onSchemaChange' listener. The schema will still update: Cannot use GraphQLNonNull "Int!" from another module or realm.
`

Likely caused by duplicate `graphql` package in federation-subscription-tools folder compared to subscriptions-server
But I suspect this is because of my meddling with graphql in https://github.com/apollosolutions/federation-subscription-tools/pull/6
<img width="1254" alt="Screenshot 2021-07-20 at 01 01 07" src="https://user-images.githubusercontent.com/445122/126233060-320a3127-12bd-4c2d-9274-5eba62bba5cd.png">

**Comment by tot-ra** [comment]
Adding resolutions as suggested in https://github.com/graphql-boilerplates/typescript-graphql-server/issues/136 didn't help

**Comment by tot-ra** [comment]
so I have two solutions
First one is to use npm instead of mounting the lib & linking it
https://github.com/tot-ra/federation-subscription-tools/tree/stable

Second one is to not use lib at all in subscriptions service
https://github.com/tot-ra/federation-subscription-tools/tree/stable-no-lib

**Comment by flyboarder** [comment]
This package has been updated and now includes typescript, additionally onSchemaChange is no longer used.
